### ISSUE TITLE
no vera++ package in OpenBSD bootstrap.sh file

### ISSUE THREAD

**Issue by kmonticolo** [mcandre/tonixxx#34]
no vera++ package is available on ftp, but mentioned in tonixxx/examples/fewer-buildbot-openbsd/bootstrap.sh

**Comment by mcandre** [comment]
Commented code cannot be tested :P

Thanks for pointing this out!

**Comment by mcandre** [comment]
Looks like I somehow lost this fix in a bad merge, will re-apply soon with #67
